# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/iomeval',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/iomeval',
                'lib_path': 'iomeval'},
  'syms': {'iomeval.core': {'iomeval.core.foo': ('core.html#foo', 'iomeval/core.py')}}}
