"""Load API keys from `.env`, count tokens, and read the packaged prompts

Docs: https://franckalbinet.github.io/iomeval/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['n_tokens', 'load_prompt']

# %% ../nbs/00_core.ipynb #beb9cc4d
import os
from pathlib import Path
from fastcore.all import *
import tiktoken

# %% ../nbs/00_core.ipynb #92892976
def _load_dotenv():
    "Load `.env` from the project root, unless the environment sets `ANTHROPIC_API_KEY` or `MISTRAL_API_KEY`"
    if os.getenv('ANTHROPIC_API_KEY') or os.getenv('MISTRAL_API_KEY'): return
    try:
        from dotenv import load_dotenv
        env_path = Path(__file__).parent.parent / '.env'
        if env_path.exists():
            load_dotenv(env_path)
    except (ImportError, NameError): pass  # NameError: a notebook has no `__file__`

# %% ../nbs/00_core.ipynb #3b03aa33
_load_dotenv()

# %% ../nbs/00_core.ipynb #5b13d7c8
def n_tokens(
    text:str,         # Text to count tokens in
    model:str='gpt-4' # OpenAI model whose tiktoken encoding to use
    ) -> int:         # Number of tokens
    "Count the tokens in `text` with tiktoken"
    enc = tiktoken.encoding_for_model(model)
    return len(enc.encode(text))

# %% ../nbs/00_core.ipynb #38e58cd5
def load_prompt(
    name:str,               # Prompt file name without `.md`, such as `'srf_ccps'`
    path:Path|str|None=None # Folder of prompt files; `None` uses the prompts shipped with the package
    ) -> str:               # Prompt text
    "Read the prompt `name` from `path`"
    if path is None:
        try: path = Path(__file__).parent / 'files' / 'prompts'
        except NameError: path = Path('files/prompts')  # A notebook has no `__file__`
    return (Path(path)/f'{name}.md').read_text()
