# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_curator.ipynb.

# %% auto #0
__all__ = ['app', 'rt', 'status_colors', 'get_reports', 'fmt_status', 'get_headings', 'ReportCard', 'StatusSteps',
           'HeadingsEditor', 'SectionsSelector', 'main']

# %% ../nbs/06_curator.ipynb #3390c18a
#| export
# | default_exp curator

# %% ../nbs/06_curator.ipynb #1206285c
from fasthtml.common import *
from fasthtml.jupyter import *
from monsterui.all import *
from fastcore.script import call_parse
from .pipeline import Report, load_report
from pathlib import Path
from mistocr.core import read_pgs
from mistocr.refine import apply_hdg_fixes
from starlette.requests import Request
import re

# %% ../nbs/06_curator.ipynb #e9f822a4
app, rt = fast_app(
    title='IOM Curator',
    hdrs=Theme.slate.headers(mode='light', radii='small'),
    live=True
)

# %% ../nbs/06_curator.ipynb #2e88d68c
def get_reports(base_path:str='files/test') -> list[Report]:
    "Load all reports from results/*.json in base_path"
    results_dir = Path(base_path)/'results'
    return [load_report(p.stem, base_path) for p in results_dir.glob('*.json')]

# %% ../nbs/06_curator.ipynb #64052a19
def fmt_status(status): return status.replace('_', ' ').title()

# %% ../nbs/06_curator.ipynb #2445e37c
def get_headings(md_path):
    md = read_pgs(md_path)
    return re.findall(r'^#+\s+.*$', md, re.MULTILINE)

# %% ../nbs/06_curator.ipynb #a879a255
status_colors = dict(pending='amber', headings_reviewed='blue', sections_selected='purple', verified='green')

# %% ../nbs/06_curator.ipynb #b4b48888
def ReportCard(r:Report):
    title = r.ev.meta.get('Title', 'Untitled')
    title_short = title[:60] + '...' if len(title) > 60 else title
    year = r.ev.meta.get('Year', 'n/a')
    return Card(
        Div(cls='space-y-1 uk-width-expand')(
            H5(title_short.upper(), title=title, cls="font-bold text-sm"),
            DivFullySpaced(
                DivLAligned(
                    Label(fmt_status(r.curation_status), cls=f'bg-{status_colors[r.curation_status]}-500 text-white'),
                    Small(f"Year: {year}", cls=TextT.muted),
                    Small(f"ID: {r.id[:5]}...", cls=TextT.muted),
                    A("Report", href=r.pdf_url, target='_blank', cls='text-sm'+AT.primary)
                ),
                Button("Curate", hx_get=f'/report/{r.id}', hx_target='#editor', cls='h-8 uk-btn-xs'+ButtonT.primary)
            )
        ),
        cls='mb-1 p-2'
    )

# %% ../nbs/06_curator.ipynb #6628a7c7
def StatusSteps(status):
    steps = ['pending', 'headings_reviewed', 'sections_selected', 'verified']
    labels = ['Clean Headings', 'Select Sections', 'Verified']
    current_idx = steps.index(status)
    
    return Steps(*[
        LiStep(label, cls=StepT.success if i <= current_idx else StepT.neutral)
        for i, label in enumerate(labels)
    ], cls='mb-4 w-full')


    

# %% ../nbs/06_curator.ipynb #b5fab25f
def HeadingsEditor(r:Report):
    headings = get_headings(r.md_path)
    title = r.ev.meta.get('Title', 'Untitled')
    return Div(
        H5(title, cls='font-bold mb-2 text-sm'),
        StatusSteps(r.curation_status),
        Form(
            Div(*[
                Input(value=h, name=f'heading_{i}', cls='mb-1 w-full font-mono text-xs')
                for i, h in enumerate(headings)
            ], 
            cls='space-y-1 max-h-[60vh] overflow-y-auto px-2 py-2 bg-slate-50 rounded border border-slate-200'
            ),
            Hidden(name='report_id', value=r.id),
            DivCentered(Button("Save & Mark Reviewed", type='submit', cls=ButtonT.primary), cls='w-full'),
            hx_post=f'/report/{r.id}/save-headings',
            hx_target='#editor'
        )
    )

# %% ../nbs/06_curator.ipynb #5a294898
def SectionsSelector(r:Report):
    headings = get_headings(r.md_path)
    title = r.ev.meta.get('Title', 'Untitled')[:60]
    return Div(
        H5(title, cls='font-bold mb-2 text-sm'),
        StatusSteps(r.curation_status),
        Form(
            Div(
                Table(
                    Tbody(*[
                        Tr(
                            Td(CheckboxX(name=f'hdg_{i}'), cls='w-8 !py-1'),
                            Td(h, cls='font-mono text-xs !py-1'),
                            cls='border-b'
                        )
                        for i, h in enumerate(headings)
                    ]),
                    cls='w-full uk-table-middle'
                ),
                cls='max-h-[60vh] overflow-y-auto bg-slate-50 rounded border border-slate-200'
            ),
            DivCentered(
                DivLAligned(
                    Button("Save Selection", type='submit', cls=ButtonT.primary), 
                    Span("0 tokens", id='token-count', cls='ml-4 text-sm'+TextT.muted)
                ),
                cls='mt-2'),
            hx_post=f'/report/{r.id}/save-sections',
            hx_target='#editor'
        ),
        Button("← Back to Headings", hx_post=f'/report/{r.id}/reset-to-pending', hx_target='#editor', cls='mt-2')
    )

# %% ../nbs/06_curator.ipynb #6343bba3
@call_parse
def main(host:str='0.0.0.0', port:int=5001):
    "Run the curator app"
    serve(host=host, port=port)

if __name__ == "__main__": main()
