"""Download the documents of IOM evaluations, one folder per evaluation

Docs: https://franckalbinet.github.io/iomeval/downloaders.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_downloaders.ipynb.

# %% auto #0
__all__ = ['download_eval', 'download_evals']

# %% ../nbs/02_downloaders.ipynb #45d69fc4
from pathlib import Path
from fastcore.all import *
from urllib.parse import urlparse
from functools import partial

from .readers import load_evals, default_config, Evaluation

# %% ../nbs/02_downloaders.ipynb #b8bfe569
def download_eval(
    eval:Evaluation,                   # Evaluation whose documents to download
    dst:str='files/test/eval_reports', # Folder to create the evaluation's folder in
    cfg:dict=default_config            # Names of the `id`, `docs` and `url` fields
    )->Path:                           # The evaluation's folder, `dst/<id>/`
    "Download every document of `eval` to `dst/<id>/`, overwriting files with the same name"
    eval_dir = Path(dst)/getattr(eval, cfg.id)
    eval_dir.mkdir(parents=True, exist_ok=True)
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
    for doc in getattr(eval, cfg.docs):
        url = doc[cfg.url]
        fname = Path(urlparse(url).path).name
        dest = eval_dir/fname
        urlsave(url, dest, headers=headers)
    return eval_dir

# %% ../nbs/02_downloaders.ipynb #f8f41ecb
def download_evals(
    evals:L,                           # Evaluations, or a single `Evaluation`
    dst:str='files/test/eval_reports', # Folder to create the evaluations' folders in
    cfg:dict=default_config,           # Names of the `id`, `docs` and `url` fields
    n_workers:int=4                    # Number of parallel downloads
)->L:                                  # The evaluations' folders
    "Download the documents of `evals` in parallel, one folder per evaluation"
    if not isinstance(evals, L): evals = L(evals) if isinstance(evals, list) else L([evals])
    return parallel(partial(download_eval, dst=dst, cfg=cfg), evals, n_workers=n_workers, progress=True)
