"""Parse a report's headings, choose its core sections from a list of headings or with an LLM, and extract their text

Docs: https://franckalbinet.github.io/iomeval/extract.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_extract.ipynb.

# %% auto #0
__all__ = ['CoreSectionsOutput', 'HeadingDict', 'create_heading_dict', 'heading_to_key', 'find_path', 'rm_nested',
           'headings_to_paths', 'get_text', 'identify_core_sections', 'get_h1_title', 'join_sections',
           'extract_selected', 'extract_sections']

# %% ../nbs/03_extract.ipynb #bb2a3b4d
from fastcore.all import *
from operator import getitem
from pydantic import BaseModel
from mistocr.refine import structured_llm
from aidialog.msg_parts import mk_msg
from exhash.outline import open_doc
import logging
from .core import load_prompt

# %% ../nbs/03_extract.ipynb #e33b8b22
class CoreSectionsOutput(BaseModel):
    "Identify the core sections of the report"
    section_paths: list[list[str]]
    reasoning: str

# %% ../nbs/03_extract.ipynb #fb7fe4a0
class HeadingDict(dict):
    "Nested dict of section titles; each value holds its section's Markdown, heading and subsections included, in `text`"
    text = ''

def create_heading_dict(md:str # Markdown text of full report
                       ) -> HeadingDict: # Nested dict of the report's headings keyed by title
    "Parse the headings of `md` with exhash's `open_doc` into a nested dict keyed by heading title"
    def conv(sec):
        res = HeadingDict({c.title: conv(c) for c in sec.values()})
        res.text = sec.src
        return res
    # Leading newline: `open_doc` fetches a string that starts with a URL instead of parsing it
    return conv(open_doc('\n' + md))


# %% ../nbs/03_extract.ipynb #42dcbe92
def heading_to_key(hdg:str # Raw markdown heading like "## 1. Intro ..."
                  ) -> str: # Heading text without markdown prefix
    "Title of the raw heading `hdg`, without its `#` prefix"
    return hdg.lstrip('#').strip()

# %% ../nbs/03_extract.ipynb #dd600bdc
def find_path(hdgs:dict, # Nested dict from `create_heading_dict`
              key:str    # Heading title to find
             ) -> list[str]: # Titles from the top level down to `key`; empty if `key` is not in `hdgs`
    "Find the path of titles to the heading `key` in `hdgs`"
    for k in hdgs.keys():
        if k == key: return [k]
        res = find_path(hdgs[k], key)
        if res: return [k] + res
    return []

# %% ../nbs/03_extract.ipynb #7b6ffa03
def rm_nested(paths:list[list[str]] # Section paths, each a list of titles
             ) -> list[list[str]]:  # The paths that don't extend another path, shortest first
    "Drop the paths that extend another path in `paths`"
    paths = sorted(paths, key=len)
    keep = []
    for p in paths:
        if not any(p[:len(k)] == k for k in keep): keep.append(p)
    return keep

# %% ../nbs/03_extract.ipynb #84e7a79e
def headings_to_paths(hdgs:dict,                  # Nested dict from `create_heading_dict`
                      selected_headings:list[str] # Raw headings like `"## 1. Intro ..."`
                     ) -> list[list[str]]:        # Paths to the selected sections, without nested ones
    "Find the paths to `selected_headings`, skipping headings that are not in `hdgs`"
    paths = [find_path(hdgs, heading_to_key(h)) for h in selected_headings]
    paths = [p for p in paths if p]
    return rm_nested(paths)

# %% ../nbs/03_extract.ipynb #518d5333
def get_text(ks:list[str], # Titles from the top level down to the section
             hdgs:dict     # Nested dict from `create_heading_dict`
            ) -> str:      # The section's Markdown, subsections included
    "Get the Markdown of the section at path `ks` in `hdgs`"
    return L(ks).reduce(getitem, hdgs).text

# %% ../nbs/03_extract.ipynb #e7c1a140
async def identify_core_sections(
    hdgs:dict,                                          # Nested dict from `create_heading_dict`
    sp:str=None,                                        # System prompt; `None` uses the `select_sections` prompt
    response_format:type[BaseModel]=CoreSectionsOutput, # Pydantic model the reply must follow
    model:str='claude-sonnet-4-5'                       # LLM to use
) -> dict:                                              # `section_paths` and `reasoning`
    "Ask an LLM for the paths to the core sections of the report outlined by `hdgs`"
    if sp is None: sp = load_prompt('select_sections')
    msg = mk_msg(f"Here is the table of contents as a nested dictionary:\n\n{hdgs}")
    return (await structured_llm(model, [msg], response_format, system=sp)).model_dump()

# %% ../nbs/03_extract.ipynb #438e0148
def get_h1_title(hdgs:dict # Nested dict from `create_heading_dict`
                ) -> str:  # The first top-level title as a Markdown H1; empty if there are no headings
    "Get the report title from `hdgs`"
    return f"# {first(hdgs.keys())}" if hdgs else ""

# %% ../nbs/03_extract.ipynb #f51f071d
def join_sections(hdgs:dict,             # Nested dict from `create_heading_dict`
                  paths:list[list[str]]  # Paths to the sections to extract
                 ) -> str:               # Report title followed by each section's text; empty if no paths
    "Concatenate the report title and the text of each section in `paths`"
    if not paths: return ""
    texts = [get_h1_title(hdgs)]
    for p in paths:
        try: texts.append(get_text(p, hdgs))
        except (KeyError, AttributeError) as e: logging.warning(f"Path not found, skipping: {p}")
    return '\n'.join(texts)


# %% ../nbs/03_extract.ipynb #f519b66c
def extract_selected(md:str,                     # Markdown text of the full report
                     selected_headings:list[str] # Raw headings like `"## 1. Intro ..."`
                    ) -> str:                    # Report title and the text of each selected section
    "Extract the sections under `selected_headings`, such as those chosen in the curator app"
    hdgs = create_heading_dict(md)
    return join_sections(hdgs, headings_to_paths(hdgs, selected_headings))


# %% ../nbs/03_extract.ipynb #cb6dd783
@delegates(identify_core_sections)
async def extract_sections(
    md:str,                            # Markdown text of the full report
    selected_headings:list[str]=None,  # Raw headings like `"## 1. Intro ..."`; `None` asks the LLM
    **kwargs                           # Passed to `identify_core_sections`
) -> str:                              # Report title and the text of each core section
    "Extract the core sections of `md`, chosen by an LLM unless you pass `selected_headings`"
    if selected_headings is not None: return extract_selected(md, selected_headings)
    hdgs = create_heading_dict(md)
    sections = await identify_core_sections(hdgs, **kwargs)
    return join_sections(hdgs, rm_nested(sections["section_paths"]))
