"""Take IOM evaluation reports from PDF to SRF and GCM mappings, saving the state at each stage

Docs: https://franckalbinet.github.io/iomeval/pipeline.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_pipeline.ipynb.

# %% auto #0
__all__ = ['logger', 'Report', 'load_report', 'map_single', 'should_force', 'PipelineResult', 'get_current_step', 'run_pipeline',
           'BatchResult', 'filter_evals', 'is_completed', 'batch_run']

# %% ../nbs/07_pipeline.ipynb #44a0b07e
from fastcore.all import *
from pathlib import Path
from .core import n_tokens, load_prompt
from .readers import load_evals, find_eval, Evaluation, eval_url
from .downloaders import download_eval
from .extract import extract_selected
from .themes import load_enbs, load_ccps, load_gcms, load_srf_outs, load_gcms_lut, fmt_enbs, fmt_ccps, fmt_srf_outs, get_srf_outs
from .mapper import mk_system_prompt, map_themes, sort_by_relevance, get_top_ids, parse_res
from mistocr.core import read_pgs
from mistocr.pipeline import pdf_to_md
from datetime import datetime
import json
import shutil
import logging
import traceback

# %% ../nbs/07_pipeline.ipynb #047209cb
logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.WARNING, format='%(name)s - %(levelname)s - %(message)s')
logger.setLevel(logging.DEBUG)

# %% ../nbs/07_pipeline.ipynb #73009447
class Report:
    "An evaluation report and its pipeline state"
    def __init__(
        self,
        ev:Evaluation,                   # The evaluation
        pdf_url:str=None,                # URL of the report PDF
        results_path:str='data/results'  # Folder of the saved report JSON files
        ):
        store_attr()
        self.id = ev.id
        self.pdf_path,self.md_path = None,None
        self.mappings,self.selected_headings = {},[]
        self.curation_status = 'pending'
        self._load_existing()

# %% ../nbs/07_pipeline.ipynb #6e1a2613
@patch
def _load_existing(self:Report):
    "Load state from saved JSON if it exists"
    p = Path(self.results_path)/f'{self.id}.json'
    if not p.exists(): return
    data = json.loads(p.read_text())
    self.mappings = data.get('mappings', {})
    self.curation_status = data.get('curation_status', 'pending')
    self.selected_headings = data.get('selected_headings', [])


# %% ../nbs/07_pipeline.ipynb #f27d90ae
@patch(cls_method=True)
def from_url(
    cls:Report,
    url:str,                         # URL of the report PDF, one of the evaluation's documents
    evals:list,                      # Evaluations to search
    results_path:str='data/results'  # Folder of the saved report JSON files
    ) -> Report:                     # Report with `pdf_url` set to `url`
    "Create a report for the evaluation that has a document at `url`"
    return cls(find_eval(evals, url, by='url'), pdf_url=url, results_path=results_path)

# %% ../nbs/07_pipeline.ipynb #6bccec97
@patch(cls_method=True)
def from_title(
    cls:Report,
    title:str,                      # Evaluation title
    evals:list,                     # Evaluations to search
    results_path:str='data/results' # Folder of the saved report JSON files
    ) -> Report:                    # Report with `pdf_url` from `eval_url`
    "Create a report for the evaluation titled `title`"
    ev = find_eval(evals, title, by='title')
    url = eval_url(ev)
    if not url: raise ValueError(f"{ev.id}: No report URL found")
    return cls(ev, pdf_url=url, results_path=results_path)

# %% ../nbs/07_pipeline.ipynb #8a6108de
@patch(cls_method=True)
def from_id(
    cls:Report,
    id:str,                         # Evaluation ID
    evals:list,                     # Evaluations to search
    results_path:str='data/results' # Folder of the saved report JSON files
    ) -> Report:                    # Report with `pdf_url` from `eval_url`
    "Create a report for the evaluation with ID `id`"
    ev = find_eval(evals, id, by='id')
    url = eval_url(ev)
    if not url: raise ValueError(f"{ev.id}: No report URL found")
    return cls(ev, pdf_url=url, results_path=results_path)

# %% ../nbs/07_pipeline.ipynb #ed425a53
@patch
def _repr_markdown_(self:Report) -> str:
    "Display report metadata and processing status in Jupyter notebooks"
    title = self.ev.meta.get('Title', 'Untitled')
    year = self.ev.meta.get('Year', 'n/a')
    org = self.ev.meta.get('Evaluation Commissioner', 'Unknown')
    
    pipeline = []
    if self.md_path: pipeline.append('✓ OCR')
    if self.curation_status == 'sections_selected': pipeline.append(f'✓ Curated ({len(self.selected_headings)} headings)')
    if self.mappings:
        mapped = ', '.join(self.mappings.keys())
        pipeline.append(f'✓ Mappings ({mapped})')
    pipeline_str = ' | '.join(pipeline) if pipeline else 'Not processed'
    
    return f"""
## Report: {title}
**Year:** {year} | **Organization:** {org}  
**ID:** `{self.id}`

**Pipeline:** {pipeline_str}  
**Curation:** {self.curation_status}

**Report:** [View Evaluation Report]({self.pdf_url})
"""

# %% ../nbs/07_pipeline.ipynb #6d634bf6
@patch
def save(self:Report,
         path:str=None  # Folder to write to; `None` uses `results_path`
        ) -> Report:    # The report, for chaining
    "Save the report's state to `<id>.json`"
    p = Path(path or self.results_path)/f'{self.id}.json'
    p.parent.mkdir(parents=True, exist_ok=True)
    data = dict(
        id=self.id,
        report_url=self.pdf_url,
        meta={**self.ev.meta, 'report_url': self.pdf_url},
        docs=self.ev.docs,
        curation_status=self.curation_status,
        selected_headings=self.selected_headings,
        mappings=self.mappings,
        timestamp=datetime.now().isoformat()
    )
    p.write_text(json.dumps(data, indent=2))
    return self

# %% ../nbs/07_pipeline.ipynb #3a58454f
def load_report(id:str,                  # Evaluation ID
                base_path:str='data'     # Folder holding `pdf/`, `md/` and `results/`
               ) -> Report:              # The report, with its saved state
    "Load the report `id` saved under `base_path`"
    results_path = Path(base_path)/'results'
    data = json.loads((results_path/f'{id}.json').read_text())
    
    ev = Evaluation(id=data['id'], meta=data['meta'], docs=data['docs'])
    report = Report(ev, pdf_url=data.get('report_url'), results_path=results_path)
    
    pdf_dir = Path(base_path)/'pdf'/id
    md_dir = Path(base_path)/'md'/id
    report.pdf_path = pdf_dir if pdf_dir.exists() else None
    report.md_path = md_dir if md_dir.exists() else None
    
    report.curation_status = data.get('curation_status', 'pending')
    report.selected_headings = data.get('selected_headings', [])
    report.mappings = data.get('mappings', {})
    
    return report

# %% ../nbs/07_pipeline.ipynb #3cfe4b55
@patch
def download(self:Report,
             dst:str='data/pdf',  # Folder to create the report's folder in
             force:bool=False      # Download again when `pdf_path` is set
            ) -> Report:           # The report, for chaining
    "Download the evaluation's documents to `dst/<id>/`"
    if self.pdf_path and not force: return self
    self.pdf_path = download_eval(self.ev, dst=dst)
    return self

# %% ../nbs/07_pipeline.ipynb #9fc305a0
@patch
async def ocr(self:Report,
              dst:str='data/md',       # Folder to create the report's Markdown folder in
              add_img_desc:bool=True,  # Add a description of each image, written by an LLM
              force:bool=False,        # OCR again when `dst/<id>/` exists
              progress:bool=False,     # Log mistocr's progress
              fix_kwargs:dict=None,    # Passed to mistocr's `fix_hdgs`
              desc_kwargs:dict=None    # Passed to mistocr's `add_img_descs`
             ) -> Report:              # The report, for chaining
    "OCR the report PDF into Markdown pages in `dst/<id>/`, and save the report"
    if (Path(dst)/self.id).exists() and not force: return self
    if self.pdf_path is None: raise ValueError("Call download() first")
    if self.pdf_url: pdf_file = self.pdf_path/Path(self.pdf_url).name
    else: pdf_file = first(self.pdf_path.glob('*.pdf'))
    await pdf_to_md(pdf_file, Path(dst)/self.id, add_img_desc=add_img_desc, progress=progress, fix_kwargs=fix_kwargs, desc_kwargs=desc_kwargs)
    self.md_path = Path(dst)/self.id
    self.save(self.results_path)
    return self

# %% ../nbs/07_pipeline.ipynb #f90d9203
@patch
def get_sections(self:Report) -> str: # Report title and the text of each selected section
    "Extract the sections under `selected_headings` from the OCR'd pages"
    if self.md_path is None: raise ValueError("Call ocr() first")
    if self.curation_status != 'sections_selected': raise ValueError("Curation required: use curator app to select headings first")
    if not self.selected_headings: raise ValueError("No headings selected")
    return extract_selected(read_pgs(self.md_path), self.selected_headings)

# %% ../nbs/07_pipeline.ipynb #f7b5bf6c
@patch
def ensure_sp(self:Report) -> None:
    "Build the report system prompt from the selected sections, unless the report already has one"
    if not hasattr(self, '_sp'): self._sp = mk_system_prompt(self.get_sections())

# %% ../nbs/07_pipeline.ipynb #5f51ae13
@delegates(map_themes)
async def map_single(sp,                         # Report system prompt from `mk_system_prompt`
                     theme_type,                 # `'enbs'`, `'ccps'`, `'gcms'` or `'outs'`
                     path=None,                  # Folder of theme files; `None` uses the files shipped with the package
                     model='claude-haiku-4-5',   # LLM to use
                     gcm_ids=None,               # GCM objective IDs whose linked outputs to map, for `'outs'`
                     **kwargs                    # Passed to `map_themes`
                    ) -> list[dict]:             # Score dicts from `parse_res`
    "Map the report in `sp` against one theme set, with its prompt and formatting"
    if theme_type == 'enbs': res = await map_themes(sp, fmt_enbs(load_enbs(path)), load_prompt('srf_enablers'), model, **kwargs)
    elif theme_type == 'ccps': res = await map_themes(sp, fmt_ccps(load_ccps(path)), load_prompt('srf_ccps'), model, **kwargs)
    elif theme_type == 'gcms': res = await map_themes(sp, load_gcms(path), load_prompt('gcms'), model, **kwargs)
    elif theme_type == 'outs':
        srf_obj, gcm_lut = load_srf_outs(path), load_gcms_lut(path)
        output_ids = get_srf_outs(gcm_lut, gcm_ids)
        res = await map_themes(sp, fmt_srf_outs(srf_obj, output_ids), load_prompt('srf_outputs'), model, **kwargs)
    return parse_res(res)

# %% ../nbs/07_pipeline.ipynb #4c1885d3
@patch
async def map_enbs(self:Report,
                   force:bool=False,  # Map again when the theme set is in `mappings`
                   **kwargs           # Passed to `map_single`, such as `path` or `model`
                  ) -> Report:        # The report, for chaining
    "Map the selected sections against the SRF enablers, and save the report"
    if 'enbs' in self.mappings and not force: return self
    self.ensure_sp()
    self.mappings['enbs'] = await map_single(self._sp, 'enbs', **kwargs)
    self.save(self.results_path)
    return self

# %% ../nbs/07_pipeline.ipynb #67574163
@patch
async def map_ccps(self:Report,
                   force:bool=False,  # Map again when the theme set is in `mappings`
                   **kwargs           # Passed to `map_single`, such as `path` or `model`
                  ) -> Report:        # The report, for chaining
    "Map the selected sections against the SRF cross-cutting priorities, and save the report"
    if 'ccps' in self.mappings and not force: return self
    self.ensure_sp()
    self.mappings['ccps'] = await map_single(self._sp, 'ccps', **kwargs)
    self.save(self.results_path)
    return self

# %% ../nbs/07_pipeline.ipynb #5253ce14
@patch
async def map_gcms(self:Report,
                   force:bool=False,  # Map again when the theme set is in `mappings`
                   **kwargs           # Passed to `map_single`, such as `path` or `model`
                  ) -> Report:        # The report, for chaining
    "Map the selected sections against the GCM objectives, and save the report"
    if 'gcms' in self.mappings and not force: return self
    self.ensure_sp()
    self.mappings['gcms'] = await map_single(self._sp, 'gcms', **kwargs)
    self.save(self.results_path)
    return self

# %% ../nbs/07_pipeline.ipynb #c9110a90
@patch
async def map_outs(self:Report,
                   gcm_ids=None,      # GCM objective IDs whose linked outputs to map; `None` uses the top GCM objective
                   force:bool=False,  # Map again when the outputs are in `mappings`
                   **kwargs           # Passed to `map_single`, such as `path` or `model`
                  ) -> Report:        # The report, for chaining
    "Map the selected sections against the SRF outputs linked to `gcm_ids`, and save the report"
    if 'outs' in self.mappings and not force: return self
    self.ensure_sp()
    if gcm_ids is None:
        top_ids = get_top_ids(self.mappings.get('gcms', []))
        if not top_ids: return self
        gcm_ids = [top_ids[0]]
    self.mappings['outs'] = await map_single(self._sp, 'outs', gcm_ids=gcm_ids, **kwargs)
    self.save(self.results_path)
    return self

# %% ../nbs/07_pipeline.ipynb #fc37da1c
@patch
async def map_all(self:Report,
                  **kwargs  # Passed to each `map_*` method
                 ) -> Report:  # The report, for chaining
    "Run `map_enbs`, `map_ccps`, `map_gcms` and `map_outs` in order"
    for f in (self.map_enbs, self.map_ccps, self.map_gcms, self.map_outs): await f(**kwargs)
    return self

# %% ../nbs/07_pipeline.ipynb #b63be3f5
def should_force(force,     # `True` or `False` for every step, or a set of step names
                 step       # Step name, such as `'ocr'`
                ) -> bool:  # Whether to run `step` again
    "Check whether `force` applies to `step`"
    if isinstance(force, bool): return force
    return step in force

# %% ../nbs/07_pipeline.ipynb #8cf30346
class PipelineResult:
    "Outcome of `run_pipeline` for one report"
    def __init__(self,
                 report,     # The report, in its final state
                 status,     # `'completed'`, `'awaiting_curation'` or `'failed'`
                 error=None, # Error message, when `status` is `'failed'`
                 step=None   # Stage the run stopped at, when it did not complete
                ):
        store_attr()

# %% ../nbs/07_pipeline.ipynb #51cc0271
def get_current_step(report # Report to check
                    ) -> str: # `'ocr'`, `'curation'` or `'mapping'`
    "Infer the stage `report` is at from its state"
    if not report.md_path: return 'ocr'
    if report.curation_status != 'sections_selected': return 'curation'
    return 'mapping'

# %% ../nbs/07_pipeline.ipynb #0dd9587d
async def run_pipeline(evals:list,                  # Evaluations to search
                       url:str=None,                # URL of the report PDF
                       id:str=None,                 # Evaluation ID
                       title:str=None,              # Evaluation title
                       base_path:str='data',        # Folder holding `pdf/`, `md/` and `results/`
                       add_img_desc:bool=True,      # Add image descriptions during OCR
                       fix_kwargs:dict=None,        # Passed to mistocr's `fix_hdgs`
                       desc_kwargs:dict=None,       # Passed to mistocr's `add_img_descs`
                       force:bool|set=False,        # `True` to run every step again, or a set of step names
                       delete_pdf:bool=True,        # Delete the PDF folder after OCR
                       verbose:bool=False,          # Log each step
                       **kwargs                     # Passed to the `map_*` methods, such as `model`
                      ) -> PipelineResult:          # The report and how far the run got
    "Run the pipeline on one evaluation as far as it can go"
    if sum(x is not None for x in (url, id, title)) != 1:
        raise ValueError("Provide exactly one of: url, id, title")
    base = Path(base_path)
    pdf_dst, md_dst, results_path = base/'pdf', base/'md', base/'results'
    log = logger.info if verbose else lambda x: None
    
    if url: report = Report.from_url(url, evals, results_path=results_path)
    elif id: report = Report.from_id(id, evals, results_path=results_path)
    else: report = Report.from_title(title, evals, results_path=results_path)
    
    try: report = load_report(report.id, base_path=base_path)
    except FileNotFoundError: pass
    
    try:
        if not report.md_path or should_force(force, 'ocr'):
            if not report.pdf_path or should_force(force, 'download'):
                log("Downloading PDF...")
                report.download(dst=pdf_dst, force=should_force(force, 'download'))
            log("Running OCR...")
            await report.ocr(
                dst=md_dst, 
                add_img_desc=add_img_desc, 
                force=should_force(force, 'ocr'), 
                progress=verbose, 
                fix_kwargs=fix_kwargs, 
                desc_kwargs=desc_kwargs)

        if delete_pdf and report.pdf_path:
            shutil.rmtree(report.pdf_path)
            report.pdf_path = None
                
        if report.curation_status != 'sections_selected':
            report.save()
            log("Awaiting curation. Use curator app to select headings, then re-run.")
            return PipelineResult(report, 'awaiting_curation', step='curation')
        
        log("Mapping enablers...")
        await report.map_enbs(force=should_force(force, 'enbs'), **kwargs)
        log("Mapping CCPs...")
        await report.map_ccps(force=should_force(force, 'ccps'), **kwargs)
        log("Mapping GCM objectives...")
        await report.map_gcms(force=should_force(force, 'gcms'), **kwargs)
        log("Mapping outputs...")
        await report.map_outs(force=should_force(force, 'outs'), **kwargs)
        log("Pipeline complete!")
        return PipelineResult(report, 'completed')
    
    except Exception as e:
        step = get_current_step(report)
        logger.error(f"{report.id[:8]}... failed at {step}: {e}\n{traceback.format_exc()}")
        return PipelineResult(report, 'failed', error=str(e), step=step)

# %% ../nbs/07_pipeline.ipynb #b002bb4c
class BatchResult:
    "Result of running pipeline on a batch of evaluations"
    def __init__(self,
                 completed=None,         # IDs of the reports that completed
                 awaiting_curation=None, # IDs of the reports that wait for curation
                 failed=None,            # One dict per failure, with `id`, `step` and `error`
                 skipped=None            # IDs of the reports skipped because they were already complete
                ):
        store_attr()
        self.completed = completed or []
        self.awaiting_curation = awaiting_curation or []
        self.failed = failed or []
        self.skipped = skipped or []
    
    def save(self, path):
        "Save the result as JSON at `path`"
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        data = dict(completed=self.completed, awaiting_curation=self.awaiting_curation, 
                    failed=self.failed, skipped=self.skipped)
        Path(path).write_text(json.dumps(data, indent=2))

# %% ../nbs/07_pipeline.ipynb #f72b5d42
def filter_evals(evals,      # Evaluations to filter
                 year=None,  # Keep the evaluations of this `Year`, such as `'2023'`
                 ids=None    # Keep the evaluations with these IDs; takes precedence over `year`
                ) -> list:   # The kept evaluations, or `evals` when neither filter is set
    "Keep the evaluations in `ids`, or else those of `year`"
    if ids: return [e for e in evals if e.id in ids]
    if year: return [e for e in evals if e.meta.get('Year') == year]
    return evals


# %% ../nbs/07_pipeline.ipynb #7c691f19
def is_completed(report # Report to check
                ) -> bool: # Whether `mappings` has all four theme sets
    "Check whether `report` has been mapped against every theme set"
    required = {'enbs', 'ccps', 'gcms', 'outs'}
    return required.issubset(report.mappings.keys()) if report.mappings else False

# %% ../nbs/07_pipeline.ipynb #9a36dbcc
async def batch_run(
    evals,                        # Evaluations to run
    base_path:str='../../data',   # Folder holding `pdf/`, `md/` and `results/`
    year:str=None,                # Keep the evaluations of this year, such as `'2023'`
    ids:list=None,                # Keep the evaluations with these IDs; takes precedence over `year`
    force:bool|set=False,         # `True` to run every step again, or a set of step names
    stop_after:int=None,          # Stop after N reports; not implemented yet
    delete_pdf:bool=False,        # Delete each report's PDF folder after OCR
    add_img_desc:bool=True,       # Add image descriptions during OCR
    fix_kwargs:dict=None,         # Passed to mistocr's `fix_hdgs`
    desc_kwargs:dict=None,        # Passed to mistocr's `add_img_descs`
    **kwargs                      # Passed to `run_pipeline`, such as `model`
) -> BatchResult:                 # IDs of the evaluations, grouped by outcome
    "Run the pipeline on each evaluation, and save a summary of the run"
    filtered = filter_evals(evals, year=year, ids=ids)
    result = BatchResult()
    
    for ev in filtered:
        try: report = load_report(ev.id, base_path=base_path)
        except FileNotFoundError: report = None
        
        if report and is_completed(report) and not force:
            logger.info(f"{ev.id[:8]}... skipped (already completed)")
            result.skipped.append(ev.id)
            continue
            
        url = eval_url(ev)
        if not url:
            logger.info(f"{ev.id[:8]}... failed (no report URL)")
            result.failed.append({'id': ev.id, 'step': 'url_lookup', 'error': 'Report URL not found'})
            continue
        
        pr = await run_pipeline(evals, url=url, base_path=base_path, force=force, delete_pdf=delete_pdf,
                                add_img_desc=add_img_desc, fix_kwargs=fix_kwargs, desc_kwargs=desc_kwargs, **kwargs)
        
        logger.info(f"{ev.id[:8]}... {pr.status}" + (f" ({pr.step}: {pr.error})" if pr.error else ""))
        
        if pr.status == 'completed': result.completed.append(ev.id)
        elif pr.status == 'awaiting_curation': result.awaiting_curation.append(ev.id)
        elif pr.status == 'failed': result.failed.append({'id': ev.id, 'step': pr.step, 'error': pr.error})

    timestamp = datetime.now().strftime('%Y-%m-%d_%H-%M')
    save_path = Path(base_path)/'batch_runs'/f'{timestamp}.json'
    result.save(save_path)
    return result

